# Generated by Django 4.2 on 2023-05-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='お名前')),
                ('content', models.TextField(max_length=140, verbose_name='内容')),
            ],
        ),
        migrations.DeleteModel(
            name='BoardModel',
        ),
    ]
